### PR TITLE
Upgrade to Django 4.2.

### PR DESCRIPTION
**Pull request by somexpert**
ping @ldko, @gracieflores, this is ready for review.

### CODE REVIEW

**Review by ldko — COMMENTED** [review]
Could we add the following to the test settings, so the app will run as-is?
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
```

**Comment by somexpert** [comment]
I'm a bit confused, was there something that you tried that didn't work? I know I had initially tried to run the migrations and got a DB error, but this app doesn't _use_ the database, and so it doesn't have any migrations. Did you have any trouble running the test server or the tests themselves?

**Comment by ldko** [comment]
Ah, I think I also was running migrations and got the error...not thinking about how there was no DB. Nevermind. :)

**Review by ldko — APPROVED** [review]
Works for me :+1: Thank you, Gio!

**Review by gracieflores — APPROVED** [review]
Looks good. 👍🏼

**Pull request merged**
